---
title: "Wittenberg University Analytics"
subtitle: 'Capstone - Phase 1'
author: "Kevin Steidel and Jason Freels"
date: "<br/>July 20, 2018"
output: 
  github_document:
    html_preview: no
---

## Welcome to Witt Analytics!

Throughout this program you'll be exposed to different tools and  technologies that data analysts use to communicate and collaborate on their work.  These instructions will walk you through the process of installing and configuring some of the primary tools that you'll need.

## Install the R toolchain for data science

R is an open-source programming environment for statistical computing and graphics that is supported by the R Foundation for Statistical Computing.  The R toolchain for data science includes R, along with several utilities that make an unbeatable collection of tools to for machine/statistical learning, data visualization and reproducible reporting.  

To setup the R toolchain on your machine, go to [**https://www.datasciencelabs.io/r-basics**](https://www.datasciencelabs.io/r-basics), read Chapters 1-3 and follow along with the directions in Chapter 1 to install and configure each of the components.

## Create Microsoft Teams account

Microsoft Teams is a cloud-based team collaboration tool, that is part of the Office 365 suite of applications. The core capabilities in Microsoft Teams include business messaging, calling, video meetings, and file sharing.  We'll use Teams to enable 24-hour communication between students and faculty. 

To get started fo to [**https://products.office.com/en-US/microsoft-teams/group-chat-software**](https://products.office.com/en-US/microsoft-teams/group-chat-software) and create a Teams account.  **Note:** after you finish this program you may not have access to your Wittenberg email address.  So, you are advised to use a different email address as the primary email address when creating your account.

## Create a DataCamp account

DataCamp is an learning platform offering tutorials and courses in programming and data science.  DataCamp offers short 'micro-lessons' that allow users to learn in a way that fits their schedules, on any device. We'll use DataCamp to compliment the course content and to ensure you can implement the methods learned in the courses. 

To get started go to [**https://www.datacamp.com**](https://www.datacamp.com) and create a DataCamp account. **Note:** after you finish this program you may not have access to your Wittenberg email address.  So, you are advised to use a different email address as the primary email address when creating your account.

## Create a GitHub Account

GitHub is a web-based hosting service for version control using Git. GitHub offers all of the distributed version control and source code management functionality of Git as well as adding its own features. It provides access control and several collaboration features such as bug tracking, feature requests and task management for every project.  We'll use GitHub throughout the program to collaborate on your projects. 

You'll create a GitHub account as part of setting up the R toolchain for data science, so no need to re-create it again.  However, now that you've configured your toolchain and created your accounts, you need to let us know how to connect you to the `witt-analytics` team.  To do this, make sure that you're logged into your GitHub account and go to [**https://github.com/witt-analytics/capstone-phase1/issues/1**](https://github.com/witt-analytics/capstone-phase1/issues/1).  Once there, read the instructions provided to post your email addresses.  We'll use the information you provide to get you connected to the team.

